In [ ]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier

# How to Tune Batch Size and Number of **Epochs**

In [ ]:
def create_model():
  model = Sequential()
  model.add(Dense(16, input_dim=8, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model

In [ ]:
dataset = np.loadtxt('/content/drive/MyDrive/DeepLearning/ANN/pima-indians-diabetes.csv', delimiter=',')

In [ ]:
X = dataset[:, 0:8]
y = dataset[:, 8]

In [ ]:
# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead.
  


In [ ]:
# define the grid search parameters

batch_size = [10,20, 40, 60, 80, 100]
epochs = [10, 50, 100]
param = dict(batch_size=batch_size, epochs=epochs)

grid = GridSearchCV(estimator=model, param_grid=param, cv=3, n_jobs=-1)

In [ ]:
grid_result = grid.fit(X,y)

In [ ]:
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Best: 0.717448 using {'batch_size': 10, 'epochs': 100}


In [ ]:
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

0.649740 (0.045256) with: {'batch_size': 10, 'epochs': 10}
0.648438 (0.015947) with: {'batch_size': 10, 'epochs': 50}
0.717448 (0.020505) with: {'batch_size': 10, 'epochs': 100}
0.626302 (0.028940) with: {'batch_size': 20, 'epochs': 10}
0.652344 (0.038670) with: {'batch_size': 20, 'epochs': 50}
0.701823 (0.010253) with: {'batch_size': 20, 'epochs': 100}
0.572917 (0.092951) with: {'batch_size': 40, 'epochs': 10}
0.653646 (0.017566) with: {'batch_size': 40, 'epochs': 50}
0.687500 (0.019918) with: {'batch_size': 40, 'epochs': 100}
0.565104 (0.016053) with: {'batch_size': 60, 'epochs': 10}
0.660156 (0.013902) with: {'batch_size': 60, 'epochs': 50}
0.639323 (0.016367) with: {'batch_size': 60, 'epochs': 100}
0.583333 (0.030145) with: {'batch_size': 80, 'epochs': 10}
0.645833 (0.046146) with: {'batch_size': 80, 'epochs': 50}
0.674479 (0.001841) with: {'batch_size': 80, 'epochs': 100}
0.587240 (0.077886) with: {'batch_size': 100, 'epochs': 10}
0.644531 (0.017758) with: {'batch_size': 100, 'epo

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


##How to Tune the Training Optimization Algorithm

In [ ]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier

In [ ]:
# create model
def create_model(optimizer='Adam'):
  model = Sequential()
  model.add(Dense(16, input_dim=8, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
  return model

In [ ]:
df = np.loadtxt('/content/drive/MyDrive/DeepLearning/ANN/pima-indians-diabetes.csv', delimiter=',')

In [ ]:
X = df[:, 0:8]
y = df[:, 8]

In [ ]:
model = KerasClassifier(build_fn=create_model, verbose=0, batch_size=10, epochs=100)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead.
  """Entry point for launching an IPython kernel.


In [ ]:
# define the grid search parameters
optimizer = ['SGD', 'RMSprop', 'Adagrad', 'Adadelta', 'Adam', 'Adamax', 'Nadam']
param_grid = dict(optimizer=optimizer)
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=3)
grid.get_params()
grid_result = grid.fit(X, y)

# How to Tune Learning Rate and Momentum

In [ ]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.optimizers import SGD

In [ ]:
def create_model(learn_rate=0.01, momentum=0):
  model = Sequential()
  model.add(Dense(16, input_dim=8, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))
  optimizer = SGD(lr = learn_rate, momentum=momentum)
  model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
  return model

In [ ]:
df = np.loadtxt('/content/drive/MyDrive/DeepLearning/ANN/pima-indians-diabetes.csv', delimiter=',')
X = df[:, 0:8]
y = df[:, 8]

In [ ]:
model = KerasClassifier(build_fn=create_model, batch_size=10, epochs=100, verbose=0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead.
  """Entry point for launching an IPython kernel.


In [ ]:
learning_rate=[0.001, 0.01, 0.1, 0.2, 0.3]
momentum = [0.0, 0.2, 0.4, 0.6, 0.8]
param = dict(learn_rate=learning_rate, momentum=momentum)

grid = GridSearchCV(estimator=model, param_grid=param, cv=3, n_jobs=-1)

In [ ]:
grid_result = grid.fit(X, y)

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


# How to Tune Network Weight Initialization

In [ ]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier

In [ ]:
def create_model(initializer='uniform'):
  model = Sequential()
  model.add(Dense(16, input_dim=8, activation='relu', kernel_initializer=initializer))
  model.add(Dense(1, kernel_initializer=initializer, activation='sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])
  return model

In [ ]:
df = np.loadtxt('/content/drive/MyDrive/DeepLearning/ANN/pima-indians-diabetes.csv', delimiter=',')
X = df[:, 0:8]
y = df[:, 8]

In [ ]:
model = KerasClassifier(build_fn=create_model, batch_size=10, epochs = 100, verbose=0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead.
  """Entry point for launching an IPython kernel.


In [ ]:
initializer = ['uniform', 'lecun_uniform', 'normal', 'zero', 'glorot_normal', 'glorot_uniform', 'he_normal', 'he_uniform']
param  = dict(initializer=initializer)

grid = GridSearchCV(estimator=model, param_grid=param, cv = 3, n_jobs=-1)

In [ ]:
grid_result = grid.fit(X, y)

In [ ]:
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.734375 using {'initializer': 'uniform'}
0.734375 (0.016877) with: {'initializer': 'uniform'}
0.707031 (0.005524) with: {'initializer': 'lecun_uniform'}
0.708333 (0.011201) with: {'initializer': 'normal'}
0.651042 (0.024774) with: {'initializer': 'zero'}
0.684896 (0.009744) with: {'initializer': 'glorot_normal'}
0.704427 (0.009744) with: {'initializer': 'glorot_uniform'}
0.679688 (0.035516) with: {'initializer': 'he_normal'}
0.683594 (0.003189) with: {'initializer': 'he_uniform'}


# How to Tune the Neuron Activation Function

In [ ]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier

In [ ]:
def create_model(activation='relu'):
  model = Sequential()
  model.add(Dense(16, input_dim=8, activation=activation))
  model.add(Dense(1, activation='sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])
  return model

In [ ]:
df = np.loadtxt('/content/drive/MyDrive/DeepLearning/ANN/pima-indians-diabetes.csv', delimiter=',')
X = df[:, 0:8]
y = df[:, 8]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
model = KerasClassifier(build_fn=create_model, batch_size=10, epochs=100)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead.
  """Entry point for launching an IPython kernel.


In [ ]:
activation = ['softmax', 'softplus', 'softsign', 'relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'linear']
param = dict(activation = activation)

grid = GridSearchCV(estimator=model, param_grid=param, cv=3, n_jobs=-1)

In [ ]:
grid_result = grid.fit(X_train, y_train)

Epoch 1/100
62/62 [==============================] - 1s 4ms/step - loss: 8.6889 - accuracy: 0.5554
Epoch 2/100
62/62 [==============================] - 0s 4ms/step - loss: 2.0332 - accuracy: 0.5635
Epoch 3/100
62/62 [==============================] - 0s 4ms/step - loss: 1.1349 - accuracy: 0.6010
Epoch 4/100
62/62 [==============================] - 0s 4ms/step - loss: 0.8268 - accuracy: 0.5945
Epoch 5/100
62/62 [==============================] - 0s 4ms/step - loss: 0.7531 - accuracy: 0.6270
Epoch 6/100
62/62 [==============================] - 0s 4ms/step - loss: 0.7309 - accuracy: 0.6336
Epoch 7/100
62/62 [==============================] - 0s 4ms/step - loss: 0.6760 - accuracy: 0.6303
Epoch 8/100
62/62 [==============================] - 0s 4ms/step - loss: 0.6752 - accuracy: 0.6564
Epoch 9/100
62/62 [==============================] - 0s 4ms/step - loss: 0.6413 - accuracy: 0.6450
Epoch 10/100
62/62 [==============================] - 0s 4ms/step - loss: 0.6982 - accuracy: 0.6352
Epoch 11/

In [ ]:
print(grid_result.best_score_, grid_result.best_params_)

0.6840188105901083 {'activation': 'linear'}


In [ ]:
pred_y = grid.predict(X_test)
y_pred = (pred_y > 0.5)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_pred, y_test)
acc = accuracy_score(y_pred, y_test)

In [ ]:
cm

array([[106,  40],
       [  1,   7]])

In [ ]:
acc

0.7337662337662337

# How to Tune Dropout Regularization

In [ ]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.wrappers.scikit_learn import KerasClassifier


In [ ]:
def create_model(dropout_rate=0.1):
  model = Sequential()
  model.add(Dense(16, input_dim=8, activation='relu'))
  model.add(Dropout(rate = dropout_rate))
  model.add(Dense(1, activation='relu'))
  model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])
  return model

In [ ]:
df = np.loadtxt('/content/drive/MyDrive/DeepLearning/ANN/pima-indians-diabetes.csv', delimiter=',')
X = df[:, 0:8]
y = df[:, 8]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
model = KerasClassifier(build_fn=create_model, batch_size=10, epochs=100, verbose=0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead.
  """Entry point for launching an IPython kernel.


In [ ]:
dropout_rate = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
param = dict(dropout_rate=dropout_rate)

grid = GridSearchCV(model, param_grid=param, cv=3, n_jobs=-1)

In [ ]:
grid_result = grid.fit(X_train, y_train)

In [ ]:
print(grid_result.best_score_, grid_result.best_params_)

0.6514984766642252 {'dropout_rate': 0.3}


In [ ]:
pred_y = grid.predict(X_test)
y_pred = (pred_y > 0.5)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

In [ ]:
cm

array([[106,   1],
       [ 47,   0]])

In [ ]:
acc

0.6883116883116883

# Number of neurons in hidden layer

In [ ]:
!pip install scikeras

  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 4.8.2
    Uninstalling importlib-metadata-4.8.2:
      Successfully uninstalled importlib-metadata-4.8.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
markdown 3.3.6 requires importlib-metadata>=4.4; python_version < "3.10", but you have importlib-metadata 3.10.1 which is incompatible.


In [ ]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Dropout
import scikeras
from scikeras.wrappers import KerasClassifier
#from keras.wrappers.scikit_learn import KerasClassifier

In [ ]:
def create_model(neurons=1):
  model = Sequential()
  model.add(Dense(units=neurons, input_dim=8, activation='linear', kernel_initializer='uniform'))
  model.add(Dropout(0.2))
  model.add(Dense(1, activation='sigmoid', kernel_initializer='uniform'))
  model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])
  return model

In [ ]:
df = np.loadtxt('/content/drive/MyDrive/DeepLearning/ANN/pima-indians-diabetes.csv', delimiter=',')
X = df[:, 0:8]
y = df[:, 8]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
neurons = [1, 5, 10, 15, 20, 25, 30]
model = KerasClassifier(model=create_model, batch_size=10, epochs=100, verbose=0, neurons=1)

In [ ]:
neurons = [1, 5, 10, 15, 20, 25, 30]
param = dict(neurons=neurons)

grid = GridSearchCV(estimator=model, param_grid=param, cv=3, n_jobs=-1)

In [ ]:
grid_result = grid.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/joblib/externals/loky/process_executor.py:705: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning


In [ ]:
print(grid_result.best_score_, grid_result.best_params_)

0.7133269567989796 {'neurons': 30}


In [ ]:
pred_y = grid.predict(X_test)
y_pred = (pred_y > 0.5)

In [ ]:
pred_y

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

In [ ]:
cm

array([[100,   7],
       [ 33,  14]])

In [ ]:
acc

0.7402597402597403

## Number of hidden layer

In [ ]:
import numpy as np
from sklearn.model_selection import GridSearchCV, train_test_split
from keras.layers import Dense, Dropout, Activation
from keras.models import Sequential
from scikeras.wrappers import KerasClassifier

In [ ]:
def create_model(layers, activation):
  model = Sequential()
  for i, nodes in enumerate(layers):
    if i==0:
      model.add(Dense(nodes, input_dim=X_train.shape[1]))
      model.add(Activation(activation))
      model.add(Dropout(0.2))
    else:
      model.add(Dense(nodes))
      model.add(Activation(activation))
      model.add(Dropout(0.2))

  model.add(Dense(1, activation='sigmoid', kernel_initializer='uniform'))
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model

In [ ]:
df = np.loadtxt('/content/drive/MyDrive/DeepLearning/ANN/pima-indians-diabetes.csv', delimiter=',')
X = df[:, 0:8]
y = df[:, 8]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
model = KerasClassifier(build_fn=create_model, batch_size=10, epochs=100, verbose=0, activation='sigmoid', layers=[10])

In [ ]:
layers = [[10], [20, 30], [20, 30, 40]]
activation = ['sigmoid', 'relu']
param = dict(layers=layers, activation=activation)

grid = GridSearchCV(estimator=model, param_grid=param, cv=3, n_jobs=-1)

In [ ]:
grid_result = grid.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/scikeras/wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  "``build_fn`` will be renamed to ``model`` in a future release,"


In [ ]:
print(grid_result.best_score_, grid_result.best_params_)

0.7019049896381316 {'activation': 'relu', 'layers': [10]}


In [ ]:
pred_y = grid.predict(X_test)
y_pred = (pred_y > 0.5)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

In [ ]:
cm

array([[93, 14],
       [27, 20]])

In [ ]:
acc

0.7337662337662337

========================================================================

# Keras Regressor

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import GridSearchCV, train_test_split
from keras.layers import Dense, Dropout
from keras.models import Sequential
from scikeras.wrappers import KerasRegressor

In [ ]:
def create_model(activation='relu'):
  model = Sequential()
  model.add(Dense(16, input_dim=X_train.shape[1], activation=activation))
  model.add(Dropout(0.2))
  model.add(Dense(1, activation='relu'))
  model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_absolute_error'])
  return model

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/DeepLearning/ANN/Complete_Deep_Learning/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1]
y = dataset.iloc[:, -1:]
geography = pd.get_dummies(X['Geography'], drop_first=True)
gender = pd.get_dummies(X['Gender'], drop_first=True)
X = pd.concat([X, geography, gender], axis=1)
X = X.drop(['Geography', 'Gender'], axis=1)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
model = KerasRegressor(build_fn=create_model, batch_size=10, epochs=100, verbose=0, activation='relu')

In [ ]:
activation = ['relu', 'linear']
param = dict(activation=activation)

grid = GridSearchCV(estimator=model, param_grid=param, cv=3, n_jobs=-1)

In [ ]:
grid_result = grid.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/scikeras/wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  "``build_fn`` will be renamed to ``model`` in a future release,"


In [ ]:
print(grid_result.best_score_, grid_result.best_params_)

-0.2563089221127963 {'activation': 'relu'}


In [ ]:
y_pred = grid.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

accuracy_score(y_test, y_pred)

0.7975